In [1]:
import pandas as pd
d=pd.read_csv("FINAL Dataset.csv")
d

,S.No,District,Year,Season,Crop,Rainfall(mm),Minimum Temparature(C),Maximum Temperature (C),Ph,N(Kg/Hectar),P(Kg/Hectar),K(Kg/Hectar),Zn(ppm),Fe(ppm),Cu(ppm),Mn(ppm),Irrigation(MBGL),Yield (Bales/Hectare)
0,1,Adilabad,2014 - 2015,Kharif,cotton(lint),156.040000,29.1,40.5,7.55,180.00,17.60,284.00,1.350,14.00,0.58,12.88,NaN,1.88
1,2,Adilabad,2015 - 2016,Kharif,cotton(lint),165.740000,26.1,37.6,7.55,180.00,17.60,284.00,1.350,14.00,0.58,12.88,NaN,2.49
2,3,Adilabad,2016 - 2017,Kharif,cotton(lint),240.520000,27.3,38.3,7.55,180.00,17.60,284.00,1.350,14.00,0.58,12.88,14.70,2.72
3,4,Adilabad,2017 - 2018,Kharif,cotton(lint),180.180000,27.6,37.4,7.55,180.00,17.60,284.00,1.350,14.00,0.58,12.88,13.95,3.15
4,5,Adilabad,2018 - 2019,Kharif,cotton(lint),256.060000,NaN,NaN,7.55,180.00,17.60,284.00,1.350,14.00,0.58,12.88,14.83,2.55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1131,1132,Warangal urban,2019 - 2020,rabi,Rice,15.042900,9.6,44.9,5.50,162.69,18.08,215.84,1.833,4.67,2.76,14.38,3.85,3.80
1132,1133,Yadadri,2016 - 2017,rabi,Rice,5.171429,28.3,41.8,6.54,170.70,34.10,283.10,3.200,8.30,1.60,7.20,9.41,3.84
1133,1134,Yadadri,2017 - 2018,rabi,Rice,11.285714,20.0,35.1,6.54,170.70,34.10,283.10,3.200,8.30,1.60,7.20,9.58,3.62
1134,1135,Yadadri,2018 - 2019,rabi,Rice,6.571429,NaN,NaN,6.54,170.70,34.10,283.10,3.200,8.30,1.60,7.20,13.64,3.53
1135,1136,Yadadri,2019 - 2020,rabi,Rice,11.271429,12.2,45.2,6.54,170.70,34.10,283.10,3.200,8.30,1.60,7.20,9.60,3.55

In [2]:
d.isna().sum()

S.No                         0
District                     0
Year                         0
Season                       0
Crop                         0
Rainfall(mm)                 0
Minimum Temparature(C)     264
Maximum Temperature (C)    264
Ph                           0
N(Kg/Hectar)                 0
P(Kg/Hectar)                 0
K(Kg/Hectar)                 0
Zn(ppm)                      0
Fe(ppm)                      0
Cu(ppm)                      0
Mn(ppm)                      0
Irrigation(MBGL)           142
Yield (Bales/Hectare)       16
dtype: int64

In [3]:
for i in d.columns:
    print("col :",i)
    print(d[i].unique(),len(d[i].unique()))
    print("\n")

col : S.No
[   1    2    3 ... 1134 1135 1136] 1136


col : District
['Adilabad' 'Bhadradri' 'Jagitial' 'Jangoan' 'Jayashankar' 'Jogulamba'
 'Kamareddy' 'Karimnagar' 'Khammam' 'Komaram bheem asifabad' 'Mahabubabad'
 'Mahbubnagar' 'Mancherial' 'Medak' 'Medchal' 'Mulugu' 'Nagarkurnool'
 'Nalgonda' 'Narayanapet' 'Nirmal' 'Nizamabad' 'Peddapalli' 'Rajanna'
 'Rangareddy' 'Sangareddy' 'Siddipet' 'Suryapet' 'Vikarabad' 'Wanaparthy'
 'Warangal' 'Warangal urban' 'Yadadri'] 32


col : Year
['2014 - 2015' '2015 - 2016' '2016 - 2017' '2017 - 2018' '2018 - 2019'
 '2019 - 2020'] 6


col : Season
['Kharif' 'rabi'] 2


col : Crop
['cotton(lint)' 'Maize' 'Moong(Green Gram)' 'Rice' 'Groundnut'] 5


col : Rainfall(mm)
[156.04       165.74       240.52       180.18       256.06
 204.62       250.18       194.08       205.84       225.18
 212.14       127.66       191.68       221.96       198.66
 148.         111.3        184.22       237.16       170.72
 217.76       266.4        110.1        138.54        64.72
 103.34       242.58       175.98       145.38       235.12
  92.36       134.44       192.88       146.26       152.1
 235.4        165.22       212.66       196.24       197.585
 204.596      187.9066667  240.24       142.94       226.16
 265.66       211.04       174.64       150.46       191.72
  81.06        76.1        119.08       148.22        87.62
 147.06       175.1        255.84       145.5        198.78
  91.4         98.76       215.82       132.84       100.4
 186.36       198.12       210.28        91.14       160.24
 240.884      222.5        110.26       106.62        72.82
 111.58        93.52       136.65       118.0733333  122.495
 118.588      114.5433333   92.66        98.99333333 268.66
 160.56       172.76       198.7        103.5         90.82
 273.02       144.94       168.88       255.82       210.42
 136.86       226.54       244.94       218.46       125.2
 129.3        236.04        71.84        96.46       133.64
 161.36        83.84       134.92       213.84       163.86
  86.58       150.16       187.62       146.18        93.34
 196.26       109.5        117.74       124.22       114.67
 197.64       138.32        93.6        140.16       114.72
 126.98        72.24       131.1        124.5        187.74
 230.26       180.36       137.6        222.48       267.02
 168.04       138.62       232.58       155.98       137.66
  76.08       146.6         22.87142857  14.           9.18571429
  12.12857143   3.3         14.21428571  12.21428571   8.94285714
  17.9          1.51428571   9.81428571   9.51428571  10.67142857
   2.41428571  12.35714286  17.24285714   9.88571429   5.52857143
  13.65714286  13.11428571  16.77142857   5.4          4.77143
   8.35714      6.37143      2.94285714   5.          15.51428571
  15.62857143   7.77142857  12.34285714  11.77142857  20.14285714
  14.81904762  17.70357143  16.71428571  21.10952381   7.18571429
  12.31428571  11.25714286  19.85714286   6.64285714   9.65714286
  13.18571429   9.1         16.18571429  12.75714286   9.7
   8.75714286   6.91428571  14.37142857   9.6          5.85714
  11.           9.77143     24.7         10.3          3.2
   5.1          5.5         13.1          6.88571429  10.28571429
  14.78571429   7.52857143  13.40571429   7.31429      7.85714
   7.3          7.04285714  14.55714286  13.94761905  15.23928571
  13.96571429  14.25714286  13.28285714  12.23333333   2.51428571
   4.21428571   6.25714286  24.1833      10.05         3.03333
   8.15         3.16667     11.0167       4.94285714  10.34285714
  10.68571429   9.58571429   3.41428571   9.07142857   9.98571429
  14.82857143  19.75714286  16.98571429   6.84285714  11.92857143
   9.84285714  10.14285714   8.1          7.44285714  11.14285714
   4.3          7.4         12.98571429  11.64285714  10.91428571
  12.80357143  11.68571429  12.7047619    9.5          5.58571429
  10.25714286   5.8          5.91429      7.45714      7.08571
  27.617       12.4667       3.93333     13.8667      13.1667
  15.6167       0.84286     13.0143      12.5857      15.0429
   5.17142857  11.28571429   6.57142857  11.27142857] 274


col : Minimum Temparature(C)
[29.1        26.1        27.3        27.6                nan 16.8
 27.2        28.6        21.6        26.9        27.5        19.4
 26.         26.8        18.8        27.8        28.9        21.16666667
 25.1        27.1        21.2        25.4        25.8        30.5
 29.7        29.         22.1        27.7        26.7        28.5
 21.4        26.3        19.7        28.7        20.5        24.9
 25.9        24.7        19.8        21.8        26.5        20.1
 28.2        21.         19.9        18.         28.1        27.
 17.6        27.4        20.9        18.9        26.6        19.
 24.8        18.2        26.4        28.3        21.3        20.
 29.4        29.9        18.5         5.         30.4        23.4
 12.3         9.1        29.8        29.5        20.3         9.2
 29.3        22.3        14.          9.         28.4        10.7
 29.6        23.1        14.6        30.1         6.6        30.
 11.6        31.2        19.2        19.1        10.         11.5
 10.5        20.8        11.2        23.3        12.4        13.2
  7.7        27.9        10.9        30.2        19.5        10.6
  9.7        28.         22.2        11.3         9.6        24.3
 13.3        18.4        21.5        20.7        11.4        12.2       ] 114


col : Maximum Temperature (C)
[40.5 37.6 38.3 37.4  nan 45.9 44.9 38.2 37.2 45.4 36.9 37.3 44.4 38.5
 45.6 34.7 35.9 44.1 36.2 35.8 40.6 38.7 37.9 36.4 37.5 36.8 45.  39.3
 37.7 38.4 44.8 38.8 35.  36.  42.6 45.2 36.3 35.6 44.2 35.2 44.  44.7
 41.  38.  38.1 45.5 46.  38.6 36.7 36.5 34.9 35.5 45.8 34.1 34.  42.2
 35.3 36.1 43.  39.5 45.1 43.5 43.1 34.4 42.7 46.8 43.3 46.7 41.9 35.7
 46.4 41.4 41.5 33.8 44.3 34.8 43.6 43.7 42.3 42.9 41.8 35.4 46.2 41.3
 43.8 44.5 41.7 43.9 44.6 42.8 45.3 40.7 35.1 42.1 33.1 34.5 41.2 33.9
 34.6] 99


col : Ph
[7.55 5.31 7.87 6.9  7.7  8.2  7.3  7.59 6.89 7.6  7.5  7.52 7.4  7.8
 7.75 7.45 7.53 7.51 5.3  7.58 5.6  7.56 5.5  6.54] 24


col : N(Kg/Hectar)
[180.   185.2  182.76 273.3  303.16 156.17 274.7  407.29 241.   155.
 260.    97.   128.   278.7  243.15 277.5  184.6  172.   150.6  178.
 252.   301.05 290.3  196.4  285.   270.16 165.4  225.6  140.39 209.
 162.69 170.7 ] 32


col : P(Kg/Hectar)
[17.6  34.5  38.77 27.5  51.01 37.9  31.31 43.59 23.7  15.6  20.   35.02
 49.4  30.5  38.06 19.8  16.9  39.1  33.55 19.7  21.3  80.77 50.25 54.9
 28.1  37.29 34.1  27.   31.02 49.   18.08] 31


col : K(Kg/Hectar)
[284.   135.   358.86 325.   432.29 289.96 308.92 302.26 228.25 285.
 330.   268.   238.   357.   265.49 346.   232.9  296.9  276.47 331.
 323.3  490.94 256.15 231.2  355.3  302.66 251.8  275.69 265.77 552.
 215.84 283.1 ] 32


col : Zn(ppm)
[1.35   1.05   1.02   3.61   0.98   0.88   1.31   1.18   1.66   0.49
 1.56   0.75   1.65   1.43   1.733  0.62   1.1    1.6    0.882  0.35
 0.9    0.3    1.45   1.9264 3.2    1.08   0.888  1.24   1.833 ] 29


col : Fe(ppm)
[14.    3.69  8.4  38.04 18.04  7.52 11.81 34.93 16.84 15.62 17.3   9.8
 11.58 15.33  4.3   7.63 13.02 14.52 10.67 19.1  11.27  8.2   7.9  13.36
  8.3   8.78  8.14 24.42  4.67] 29


col : Cu(ppm)
[0.58  0.31  1.9   3.77  2.33  1.16  2.44  3.11  2.1   0.39  3.92  0.71
 2.2   1.63  1.91  1.24  1.36  1.32  0.97  0.99  2.68  2.13  3.05  1.45
 2.56  1.6   2.47  1.044 1.87  2.76 ] 30


col : Mn(ppm)
[12.88  7.51 14.   20.2  13.03 10.01 15.28 14.68 22.01 15.21 17.5   8.8
 16.   19.33 11.98 13.46 12.11 11.14 10.12 10.36 13.5  11.2  13.68  4.58
 15.34  7.3  11.47 10.08  9.59 14.38  7.2 ] 31


col : Irrigation(MBGL)
[  nan 14.7  13.95 14.83 14.18 13.07 12.05 12.31 11.33 11.15  7.43  9.14
  8.41 16.42 14.23 12.79 14.65 11.92 12.69 12.42 16.3  11.83  9.75  9.78
 13.82 20.81 15.52 16.84 19.31 15.65 11.86 12.7  13.56 10.43  9.15  8.32
  7.55  8.97  8.88  8.94 10.41  9.69 10.05 10.38 18.41 17.79 16.   19.43
  7.47  7.34  8.62  7.98 29.09 17.63 21.18 26.47 16.33 10.79 12.63 18.24
 12.01 20.52 17.47 13.32 14.14 16.14 12.45 12.4  14.81 15.44 15.32 11.25
 13.48 13.04 21.23 10.85 15.63 17.2  11.61  8.68 11.52 11.59 17.95 14.3
 15.06 17.98 19.44 18.37 17.24 19.93 23.9  19.45 17.53 24.12 28.74 16.03
 16.68 20.55 14.86 10.72 10.53 10.84 19.05 14.68 16.05 20.47 12.14 10.06
  7.32  7.63 11.4   9.46 10.04 11.26 17.07 12.83 15.6   3.94  6.54  5.88
  5.53  7.1   7.87  7.23  6.52  4.7   5.33  3.79  9.16 13.38  6.86  7.71
  9.8   9.54  9.31  6.45 10.74  7.9   9.64  9.92  8.31  5.94  8.04  8.49
  3.53  5.62  4.85  5.39  3.93  6.3   6.95  6.14  4.77  6.94  4.23 12.49
 10.66 15.05 12.51  3.89  6.01  5.08  3.63 11.74 20.71 15.55  7.78  6.57
 13.23  9.12  7.06  5.54 14.84 11.62  9.5   8.06  8.64 12.93  8.58 13.2
  9.44  5.58  9.42  8.96  6.29  6.7   9.33 11.28  6.48  6.06  8.95  7.31
  5.32  7.19 12.29  5.61 14.12 17.55 13.46 11.21 11.11 18.96 16.89 10.96
 11.41 17.19 10.52  6.62  8.11  8.26  9.47 10.14 16.86 12.25  6.13  5.79
  3.58  6.63  7.84  3.85  9.41  9.58 13.64  9.6 ] 224


col : Yield (Bales/Hectare)
[ 1.88   2.49   2.72   3.15   2.55   4.74   3.38   3.89   2.43   3.42
  3.2    1.94   2.8    3.4    3.03   3.16   2.19   2.88   2.52   2.92
  3.55   1.75   1.97   3.07   2.31   2.53   3.64   3.23   2.73   3.48
  3.02   3.08   2.99   3.98   2.24   3.5    2.12   2.35   3.27   2.22
  1.95   0.96   1.64   1.29   3.18   3.44   3.26   1.68   2.14   4.88
  2.47   1.59   2.74   3.21   0.5    3.69   1.53   0.89   3.36   1.65
  2.13   1.74   2.62   0.22   3.24   3.34   2.64   2.95   1.19   0.99
  3.41   4.11   3.22   3.01   2.69   4.9    1.49   1.6    2.21   1.24
  3.92   1.9    3.39   1.71   3.3    3.29   2.56   2.1    2.89   2.75
  1.48   2.66   1.7    2.82   2.26   2.25   2.46   1.61   3.1    3.12
  3.46   3.45   4.84   4.17   4.13   2.51   5.24   4.54   4.46   6.35
  5.84   4.25   5.71   5.5    7.     6.8    4.85   1.09   5.64   2.7
  4.93   5.27   5.35   6.17   6.13   4.58   4.1    4.68   5.67   6.23
  3.65   4.82   5.36   5.47   4.64   3.28   5.33   3.43   5.68   1.8
  1.27   1.45   1.2    3.11   3.93   1.54   3.71   2.67   4.3    3.14
  2.48   4.07   6.59   2.01   0.64   0.75   0.7    1.89   4.87   5.72
  6.11   8.19   4.44   5.03   5.7    6.41   6.92   6.61   8.28   2.85
  5.15   7.03   3.79   2.16   0.71   3.32   4.49   2.59   4.31   3.47
  3.17   3.25   5.2    5.25   3.99   3.66   6.97   6.42   5.8    5.53
  5.48   2.11   0.58   0.59   0.65   0.82   0.44   0.63   0.79   0.61
  0.97   0.55   0.62   0.78   0.56   0.52   0.9    0.645  0.86   0.92
  1.1    1.01   0.37   0.67   0.47   0.35   0.73   0.77   0.8    0.66
  0.51   0.91   0.07   0.57   0.54   0.4    0.68   0.43   0.46   1.
  0.81   0.29   0.41   0.24   0.74   0.33   0.31   0.69   0.84   0.45
  0.6    0.87   2.58   2.4    3.63   3.51   3.67   2.28   2.57   3.94
  4.51   3.53   2.91   2.97   3.57   3.59   1.79   2.09   2.36   3.13
  2.54   1.93   2.44   2.84   3.06   4.38   2.63   4.16   2.79   2.18
  2.38   3.33   3.05   3.37   2.68   3.6    4.2    4.15   4.     3.83
  3.7    4.34   3.09   3.88   3.74   3.31   2.96   3.19   2.02   3.
  3.76   1.91   2.23   2.07   3.04   2.33   1.43   1.37   1.66   1.76
  2.39   2.83   1.46   2.41   1.67   1.56   1.47   2.06   2.195  1.3
  1.51   2.05   1.85   2.34     nan  1.81   2.32   2.15   1.05   1.31
  1.99   1.69   2.08   2.87   2.5    1.21   2.71   1.32   2.04   2.94
 10.98   5.58   6.56   8.71   7.45   6.33   5.85   6.82   4.5    5.54
  5.92   5.41   7.91   5.98   9.75   7.29   6.98   3.54   3.77   5.22
  4.67   7.04   5.45   8.35   7.37   6.95   6.12   6.53   6.21   6.71
  6.02   7.51   6.9    6.5    6.93   6.94   6.67   6.81   5.6    5.19
  3.96   6.52   4.48   6.16   4.27   4.62   5.14   6.1    6.51  10.96
  5.3    4.98   7.13   8.16   8.67   8.27   8.8    5.83   5.77   5.94
  9.48   9.71   7.09   4.4    6.72   6.91   4.77   4.24   4.14   4.03
  6.24   4.37   6.96   6.43  10.36   8.34   8.79   6.84   7.35   7.57
  7.25   0.93   0.83   0.95   0.85   0.72   0.94   0.88   0.98   1.73
  1.07   0.826  0.833  3.72   3.78   3.82   3.61   2.81   3.87   3.8
  3.62   4.21   3.68   3.91   4.06   2.17   3.49   2.86   3.73   4.36
  4.09   4.08   3.52   3.95   2.37   1.92   4.65   4.45   2.65   3.84 ] 450

In [4]:
d[["Minimum Temparature(C)","Maximum Temperature (C)"]]=d.groupby(by=["District","Season"])[["Minimum Temparature(C)","Maximum Temperature (C)"]].apply(lambda x: x.fillna(x.mean()))

In [5]:
d["Irrigation(MBGL)"]=d.groupby(by=["District","Season"])["Irrigation(MBGL)"].apply(lambda x: x.fillna(x.mean()))

In [6]:
d.isna().sum()

S.No                        0
District                    0
Year                        0
Season                      0
Crop                        0
Rainfall(mm)                0
Minimum Temparature(C)      0
Maximum Temperature (C)     0
Ph                          0
N(Kg/Hectar)                0
P(Kg/Hectar)                0
K(Kg/Hectar)                0
Zn(ppm)                     0
Fe(ppm)                     0
Cu(ppm)                     0
Mn(ppm)                     0
Irrigation(MBGL)            0
Yield (Bales/Hectare)      16
dtype: int64

In [7]:
d=d.dropna()

In [8]:
d.isna().sum()

S.No                       0
District                   0
Year                       0
Season                     0
Crop                       0
Rainfall(mm)               0
Minimum Temparature(C)     0
Maximum Temperature (C)    0
Ph                         0
N(Kg/Hectar)               0
P(Kg/Hectar)               0
K(Kg/Hectar)               0
Zn(ppm)                    0
Fe(ppm)                    0
Cu(ppm)                    0
Mn(ppm)                    0
Irrigation(MBGL)           0
Yield (Bales/Hectare)      0
dtype: int64

In [9]:
d.to_excel("final nan.xlsx")

In [10]:
d=pd.read_excel("final nan.xlsx")
d

,Unnamed: 0,S.No,District,Year,Season,Crop,Rainfall(mm),Minimum Temparature(C),Maximum Temperature (C),Ph,N(Kg/Hectar),P(Kg/Hectar),K(Kg/Hectar),Zn(ppm),Fe(ppm),Cu(ppm),Mn(ppm),Irrigation(MBGL),Yield (Bales/Hectare)
0,0,1,Adilabad,2014 - 2015,Kharif,cotton(lint),156.040000,29.100000,40.50,7.55,180.00,17.60,284.00,1.350,14.00,0.58,12.88,14.415,1.88
1,1,2,Adilabad,2015 - 2016,Kharif,cotton(lint),165.740000,26.100000,37.60,7.55,180.00,17.60,284.00,1.350,14.00,0.58,12.88,14.415,2.49
2,2,3,Adilabad,2016 - 2017,Kharif,cotton(lint),240.520000,27.300000,38.30,7.55,180.00,17.60,284.00,1.350,14.00,0.58,12.88,14.700,2.72
3,3,4,Adilabad,2017 - 2018,Kharif,cotton(lint),180.180000,27.600000,37.40,7.55,180.00,17.60,284.00,1.350,14.00,0.58,12.88,13.950,3.15
4,4,5,Adilabad,2018 - 2019,Kharif,cotton(lint),256.060000,25.380000,39.94,7.55,180.00,17.60,284.00,1.350,14.00,0.58,12.88,14.830,2.55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1115,1131,1132,Warangal urban,2019 - 2020,rabi,Rice,15.042900,9.600000,44.90,5.50,162.69,18.08,215.84,1.833,4.67,2.76,14.38,3.850,3.80
1116,1132,1133,Yadadri,2016 - 2017,rabi,Rice,5.171429,28.300000,41.80,6.54,170.70,34.10,283.10,3.200,8.30,1.60,7.20,9.410,3.84
1117,1133,1134,Yadadri,2017 - 2018,rabi,Rice,11.285714,20.000000,35.10,6.54,170.70,34.10,283.10,3.200,8.30,1.60,7.20,9.580,3.62
1118,1134,1135,Yadadri,2018 - 2019,rabi,Rice,6.571429,20.166667,40.70,6.54,170.70,34.10,283.10,3.200,8.30,1.60,7.20,13.640,3.53
1119,1135,1136,Yadadri,2019 - 2020,rabi,Rice,11.271429,12.200000,45.20,6.54,170.70,34.10,283.10,3.200,8.30,1.60,7.20,9.600,3.55

In [11]:
d=pd.get_dummies(d)

In [12]:
d.to_excel("final catgry.xlsx")

In [13]:
d=pd.read_excel("final catgry.xlsx")
d

,Unnamed: 0.1,Unnamed: 0,S.No,Rainfall(mm),Minimum Temparature(C),Maximum Temperature (C),Ph,N(Kg/Hectar),P(Kg/Hectar),K(Kg/Hectar),...,Year_2017 - 2018,Year_2018 - 2019,Year_2019 - 2020,Season_Kharif,Season_rabi,Crop_Groundnut,Crop_Maize,Crop_Moong(Green Gram),Crop_Rice,Crop_cotton(lint)
0,0,0,1,156.040000,29.100000,40.50,7.55,180.00,17.60,284.00,...,0,0,0,1,0,0,0,0,0,1
1,1,1,2,165.740000,26.100000,37.60,7.55,180.00,17.60,284.00,...,0,0,0,1,0,0,0,0,0,1
2,2,2,3,240.520000,27.300000,38.30,7.55,180.00,17.60,284.00,...,0,0,0,1,0,0,0,0,0,1
3,3,3,4,180.180000,27.600000,37.40,7.55,180.00,17.60,284.00,...,1,0,0,1,0,0,0,0,0,1
4,4,4,5,256.060000,25.380000,39.94,7.55,180.00,17.60,284.00,...,0,1,0,1,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1115,1115,1131,1132,15.042900,9.600000,44.90,5.50,162.69,18.08,215.84,...,0,0,1,0,1,0,0,0,1,0
1116,1116,1132,1133,5.171429,28.300000,41.80,6.54,170.70,34.10,283.10,...,0,0,0,0,1,0,0,0,1,0
1117,1117,1133,1134,11.285714,20.000000,35.10,6.54,170.70,34.10,283.10,...,1,0,0,0,1,0,0,0,1,0
1118,1118,1134,1135,6.571429,20.166667,40.70,6.54,170.70,34.10,283.10,...,0,1,0,0,1,0,0,0,1,0
1119,1119,1135,1136,11.271429,12.200000,45.20,6.54,170.70,34.10,283.10,...,0,0,1,0,1,0,0,0,1,0

In [14]:
d=d.drop("Unnamed: 0",axis=1)

In [15]:
d

,Unnamed: 0.1,S.No,Rainfall(mm),Minimum Temparature(C),Maximum Temperature (C),Ph,N(Kg/Hectar),P(Kg/Hectar),K(Kg/Hectar),Zn(ppm),...,Year_2017 - 2018,Year_2018 - 2019,Year_2019 - 2020,Season_Kharif,Season_rabi,Crop_Groundnut,Crop_Maize,Crop_Moong(Green Gram),Crop_Rice,Crop_cotton(lint)
0,0,1,156.040000,29.100000,40.50,7.55,180.00,17.60,284.00,1.350,...,0,0,0,1,0,0,0,0,0,1
1,1,2,165.740000,26.100000,37.60,7.55,180.00,17.60,284.00,1.350,...,0,0,0,1,0,0,0,0,0,1
2,2,3,240.520000,27.300000,38.30,7.55,180.00,17.60,284.00,1.350,...,0,0,0,1,0,0,0,0,0,1
3,3,4,180.180000,27.600000,37.40,7.55,180.00,17.60,284.00,1.350,...,1,0,0,1,0,0,0,0,0,1
4,4,5,256.060000,25.380000,39.94,7.55,180.00,17.60,284.00,1.350,...,0,1,0,1,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1115,1115,1132,15.042900,9.600000,44.90,5.50,162.69,18.08,215.84,1.833,...,0,0,1,0,1,0,0,0,1,0
1116,1116,1133,5.171429,28.300000,41.80,6.54,170.70,34.10,283.10,3.200,...,0,0,0,0,1,0,0,0,1,0
1117,1117,1134,11.285714,20.000000,35.10,6.54,170.70,34.10,283.10,3.200,...,1,0,0,0,1,0,0,0,1,0
1118,1118,1135,6.571429,20.166667,40.70,6.54,170.70,34.10,283.10,3.200,...,0,1,0,0,1,0,0,0,1,0
1119,1119,1136,11.271429,12.200000,45.20,6.54,170.70,34.10,283.10,3.200,...,0,0,1,0,1,0,0,0,1,0

In [16]:
d.columns

Index(['Unnamed: 0.1', 'S.No', 'Rainfall(mm)', 'Minimum Temparature(C)',
       'Maximum Temperature (C)', 'Ph', 'N(Kg/Hectar)', 'P(Kg/Hectar)',
       'K(Kg/Hectar)', 'Zn(ppm)', 'Fe(ppm)', 'Cu(ppm)', 'Mn(ppm)',
       'Irrigation(MBGL)', 'Yield (Bales/Hectare)', 'District_Adilabad',
       'District_Bhadradri', 'District_Jagitial', 'District_Jangoan',
       'District_Jayashankar', 'District_Jogulamba', 'District_Kamareddy',
       'District_Karimnagar', 'District_Khammam',
       'District_Komaram bheem asifabad', 'District_Mahabubabad',
       'District_Mahbubnagar', 'District_Mancherial', 'District_Medak',
       'District_Medchal', 'District_Mulugu', 'District_Nagarkurnool',
       'District_Nalgonda', 'District_Narayanapet', 'District_Nirmal',
       'District_Nizamabad', 'District_Peddapalli', 'District_Rajanna',
       'District_Rangareddy', 'District_Sangareddy', 'District_Siddipet',
       'District_Suryapet', 'District_Vikarabad', 'District_Wanaparthy',
       'District_Warangal', 'District_Warangal urban', 'District_Yadadri',
       'Year_2014 - 2015', 'Year_2015 - 2016', 'Year_2016 - 2017',
       'Year_2017 - 2018', 'Year_2018 - 2019', 'Year_2019 - 2020',
       'Season_Kharif', 'Season_rabi', 'Crop_Groundnut', 'Crop_Maize',
       'Crop_Moong(Green Gram)', 'Crop_Rice', 'Crop_cotton(lint)'],
      dtype='object')

In [17]:
y=d['Yield (Bales/Hectare)'].values
y

array([1.88, 2.49, 2.72, ..., 3.62, 3.53, 3.55])

In [18]:
x=d.drop('Yield (Bales/Hectare)',axis=1).values
x

array([[0.00000000e+00, 1.00000000e+00, 1.56040000e+02, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [1.00000000e+00, 2.00000000e+00, 1.65740000e+02, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [2.00000000e+00, 3.00000000e+00, 2.40520000e+02, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       ...,
       [1.11700000e+03, 1.13400000e+03, 1.12857143e+01, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [1.11800000e+03, 1.13500000e+03, 6.57142857e+00, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [1.11900000e+03, 1.13600000e+03, 1.12714286e+01, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00]])

In [19]:
from sklearn.ensemble import RandomForestRegressor
rf=RandomForestRegressor()
rf.fit(x,y)

RandomForestRegressor()

In [20]:
y_pred=rf.predict(x)

In [21]:
from sklearn.metrics import mean_squared_error, r2_score
mean_squared_error(y,y_pred)

0.06624119908366069

In [22]:
r2_score(y,y_pred)

0.9820130304788685

In [23]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [24]:
rf=RandomForestRegressor()
rf.fit(x_train,y_train)

RandomForestRegressor()

In [25]:
y_pred=rf.predict(x_test)
print("r2_score",r2_score(y_test,y_pred))
print("mean_sq_err",mean_squared_error(y_test,y_pred))

r2_score 0.8544793084528688
mean_sq_err 0.5321912081540178

In [26]:
from sklearn.ensemble import BaggingRegressor
bg=BaggingRegressor()
bg.fit(x_train,y_train)

BaggingRegressor()

In [27]:
y_pred=bg.predict(x_test)
print("r2_score",r2_score(y_test,y_pred))
print("mean_sq_err",mean_squared_error(y_test,y_pred))

r2_score 0.8281243100482428
mean_sq_err 0.628575428794643

In [28]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

# Load the data


# Select relevant features and target variable
features =x
target = y

# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=42)

# Train a Random Forest model
random_forest = RandomForestRegressor(n_estimators=100, random_state=42)
random_forest.fit(X_train, y_train)

# Predict on the test set using Random Forest
y_pred = random_forest.predict(X_test)

# Evaluate the model
r2 = r2_score(y_test, y_pred)
print('R2 Score:', r2)

R2 Score: 0.8627082298796855

In [29]:
d.columns

Index(['Unnamed: 0.1', 'S.No', 'Rainfall(mm)', 'Minimum Temparature(C)',
       'Maximum Temperature (C)', 'Ph', 'N(Kg/Hectar)', 'P(Kg/Hectar)',
       'K(Kg/Hectar)', 'Zn(ppm)', 'Fe(ppm)', 'Cu(ppm)', 'Mn(ppm)',
       'Irrigation(MBGL)', 'Yield (Bales/Hectare)', 'District_Adilabad',
       'District_Bhadradri', 'District_Jagitial', 'District_Jangoan',
       'District_Jayashankar', 'District_Jogulamba', 'District_Kamareddy',
       'District_Karimnagar', 'District_Khammam',
       'District_Komaram bheem asifabad', 'District_Mahabubabad',
       'District_Mahbubnagar', 'District_Mancherial', 'District_Medak',
       'District_Medchal', 'District_Mulugu', 'District_Nagarkurnool',
       'District_Nalgonda', 'District_Narayanapet', 'District_Nirmal',
       'District_Nizamabad', 'District_Peddapalli', 'District_Rajanna',
       'District_Rangareddy', 'District_Sangareddy', 'District_Siddipet',
       'District_Suryapet', 'District_Vikarabad', 'District_Wanaparthy',
       'District_Warangal', 'District_Warangal urban', 'District_Yadadri',
       'Year_2014 - 2015', 'Year_2015 - 2016', 'Year_2016 - 2017',
       'Year_2017 - 2018', 'Year_2018 - 2019', 'Year_2019 - 2020',
       'Season_Kharif', 'Season_rabi', 'Crop_Groundnut', 'Crop_Maize',
       'Crop_Moong(Green Gram)', 'Crop_Rice', 'Crop_cotton(lint)'],
      dtype='object')